session_name: web-backoffice
start_directory: /Users/mazulo/dev/work/ashenlabs/closecare/web-backoffice

windows:
- window_name: editor
  options: {}
  panes:
  - focus: 'true'
    shell_command: nvm use stable && nvim
- window_name: shell
  options: {}
  panes:
  - focus: 'true'
    shell_command: nvm use stable
- window_name: web server
  options: {}
  panes:
  - focus: 'true'
    shell_command: nvm use stable
- window_name: mock server
  options: {}
  panes:
  - focus: 'true'
    shell_command: nvm use stable
- window_name: tests
  options: {}
  panes:
  - focus: 'true'
    shell_command: nvm use stable
