session_name: beeware
start_directory: /Users/mazulo/Dev/study/beeware_project/helloworld

windows:
- window_name: editor
  options: {}
  panes:
  - focus: 'true'
    shell_command: workon beeware && nvim
- window_name: shell
  options: {}
  panes:
  - focus: 'true'
    shell_command: workon beeware
- window_name: tests
  options: {}
  panes:
  - focus: 'true'
    shell_command: workon beeware
- window_name: server
  options: {}
  panes:
  - focus: 'true'
    shell_command: workon beeware
