session_name: business-care
start_directory: /Users/mazulo/dev/work/ashenlabs/closecare/business_care/

windows:
- window_name: editor
  options: {}
  panes:
  - focus: 'true'
    shell_command: nvm use stable && nvim
- window_name: shell
  options: {}
  panes:
  - focus: 'true'
    shell_command: nvm use stable
- window_name: web server
  options: {}
  panes:
  - focus: 'true'
    shell_command: nvm use stable
- window_name: tests
  options: {}
  panes:
  - focus: 'true'
    shell_command: nvm use stable
