session_name: cloud-endpoints
start_directory: /Users/mazulo/dev/work/ashenlabs/closecare/cloud-endpoints/

windows:
- window_name: editor
  options: {}
  panes:
  - focus: 'true'
    shell_command: nvim
- window_name: shell
  options: {}
  panes:
  - focus: 'true'
    shell_command:
- window_name: web server
  options: {}
  panes:
  - focus: 'true'
    shell_command:
