session_name: depcheckr
start_directory: /Users/mazulo/Dev/open-source/depcheckr/

windows:
- focus: 'true'
  window_name: editor
  options: {}
  panes:
  - focus: 'true'
    shell_command: workon depcheckr && nvm use stable && nvim
- window_name: servers
  options: {}
  panes:
  - focus: 'true'
    shell_command: workon depcheckr && nvm use stable
- window_name: shell
  options: {}
  panes:
  - focus: 'true'
    shell_command: workon depcheckr && nvm use stable
