session_name: dot-files
start_directory: /Users/mazulo/dev/open-source/ashenlabs/dot-files

windows:
  - focus: "true"
    window_name: editor
    options: {}
    panes:
      - focus: "true"
        shell_command: nvim
  - window_name: shell
    suppress_history: true
    options: {}
    panes:
      - focus: "true"
  - window_name: editor nvim config files
    start_directory: /Users/mazulo/.config/nvim
    suppress_history: true
    options: {}
    panes:
      - focus: "true"
        shell_command: nvim
  - window_name: .config dir
    start_directory: /Users/mazulo/.config/
    suppress_history: true
    options: {}
    panes:
      - focus: "true"
        shell_command: nvim
  - window_name: home dir
    start_directory: /Users/mazulo/
    suppress_history: true
    options: {}
    panes:
      - focus: "true"
        shell_command: nvim
