session_name: fastapi-tdd-docker
start_directory: /Users/mazulo/Dev/study/fastapi-tdd-docker/project

windows:
- focus: 'true'
  window_name: editor
  layout: e8b6,314x87,0,0,27
  options: {}
  panes:
  - focus: 'true'
    shell_command: workon fastapi-tdd-docker && nvm use stable && nvim
- layout: ebe7,489x97,0,0,28
  window_name: servers
  options: {}
  panes:
  - focus: 'true'
    shell_command: workon fastapi-tdd-docker && nvm use stable
- layout: ebe8,489x97,0,0,29
  window_name: shell
  options: {}
  panes:
  - focus: 'true'
    shell_command: workon fastapi-tdd-docker && nvm use stable
- layout: 6be0,489x97,0,0,30
  options: {}
  panes:
  - focus: 'true'
    shell_command: workon fastapi-tdd-docker && nvm use stable
