session_name: fcm-pubsub
start_directory: /Users/mazulo/dev/work/ashenlabs/ninjatrader/fcm-pubsub/

windows:
- window_name: editor
  options: {}
  panes:
  - focus: 'true'
    shell_command: nvim
- window_name: shell
  options: {}
  panes:
  - focus: 'true'
    shell_command:
- window_name: tests
  options: {}
  panes:
  - focus: 'true'
    shell_command:
- window_name: web server
  options: {}
  panes:
  - focus: 'true'
    shell_command:
