session_name: flask_slqlalchemy-stubs
start_directory: /Users/mazulo/Dev/open-source/flask_sqlalchemy-stubs/

windows:
- window_name: editor
  options: {}
  panes:
  - focus: 'true'
    shell_command: workon flask-sqlalchemy-stubs && nvim
- window_name: shell
  options: {}
  panes:
  - focus: 'true'
    shell_command: workon flask-sqlalchemy-stubs
- window_name: tests
  options: {}
  panes:
  - focus: 'true'
    shell_command: workon flask-sqlalchemy-stubs
- window_name: web server
  options: {}
  panes:
  - focus: 'true'
    shell_command: workon flask-sqlalchemy-stubs
