session_name: freightflow-web-v2
start_directory: /Users/mazulo/Dev/d7/freightflow/freightflow-web-v2

windows:
- layout: e8af,314x87,0,0,20
  window_name: editor
  options: {}
  panes:
  - focus: 'true'
    shell_command: workon freightflow-web-v2 && nvm use stable && lvim .
- layout: ebe0,489x97,0,0,21
  window_name: servers
  options: {}
  panes:
  - focus: 'true'
    shell_command: workon freightflow-web-v2 && nvm use stable
- layout: ebe1,489x97,0,0,22
  window_name: shell
  options: {}
  panes:
  - focus: 'true'
    shell_command: workon freightflow-web-v2 && nvm use stable
- layout: ebe3,489x97,0,0,24
  window_name: home
  options: {}
  panes:
  - focus: 'true'
    shell_command: nvm use stable
  start_directory: /Users/mazulo
