session_name: freightflow-web
start_directory: /Users/mazulo/Dev/d7/freightflow/freightflow-web/

windows:
- window_name: editor
  options: {}
  panes:
  - focus: 'true'
    shell_command: workon freightflow-web && nvm use stable && nvim
- window_name: shell and tests
  options: {}
  panes:
  - focus: 'true'
    shell_command: workon freightflow-web && nvm use stable
- window_name: web server
  options: {}
  panes:
  - focus: 'true'
    shell_command: workon freightflow-web && nvm use stable
- window_name: worker
  options: {}
  panes:
  - focus: 'true'
    shell_command: workon freightflow-web && nvm use stable
- window_name: elasticsearch
  options: {}
  panes:
  - focus: 'true'
    shell_command: workon freightflow-web && nvm use stable
- window_name: home    
  start_directory: /Users/mazulo
  suppress_history: true
  options: {}
  panes:
  - focus: 'true'
    shell_command: unset HISTFILE && nvm use stable
- start_directory: /Users/mazulo
  suppress_history: true
  options: {}
  panes:
  - focus: 'true'
    shell_command: unset HISTFILE && nvm use stable
