session_name: freightflow-audit
start_directory: /Users/mazulo/Dev/d7/freightflow/freightflow-audit

windows:
- window_name: editor
  options: {}
  panes:
  - focus: 'true'
    shell_command: workon freightflow-audit && nvm use stable && nvim
- window_name: servers
  options: {}
  panes:
  - focus: 'true'
    shell_command: workon freightflow-audit && nvm use stable
- window_name: shell
  options: {}
  panes:
  - focus: 'true'
    shell_command: workon freightflow-audit && nvm use stable
- window_name: home
  options: {}
  panes:
  - focus: 'true'
    shell_command: nvm use stable
  start_directory: /Users/mazulo
