session_name: heroui-components
start_directory: /Users/mazulo/dev/work/ashenlabs/avenidas/heroui-components/

windows:
- focus: 'true'
  window_name: editor
  options: {}
  panes:
  - focus: 'true'
    shell_command: nvm use stable && nvim
- window_name: server
  options: {}
  panes:
  - focus: 'true'
    shell_command: nvm use stable
- window_name: shell
  options: {}
  panes:
  - focus: 'true'
    shell_command: nvm use stable
