session_name: joby
start_directory: /Users/mazulo/Dev/open-source/joby

windows:
- focus: 'true'
  window_name: editor
  options: {}
  panes:
  - focus: 'true'
    shell_command: workon joby && nvm use stable && nvim
- window_name: servers
  options: {}
  panes:
  - focus: 'true'
    shell_command: workon joby && nvm use stable
- window_name: shell
  options: {}
  panes:
  - focus: 'true'
    shell_command: workon joby && nvm use stable
