session_name: legacy-integrator
start_directory: /Users/mazulo/dev/work/ashenlabs/closecare/legacy-integrator/

windows:
- window_name: editor
  options: {}
  panes:
  - focus: 'true'
    shell_command:  nvm use v14.17.6 nvim
- window_name: shell
  options: {}
  panes:
  - focus: 'true'
    shell_command: nvm use v14.17.6
- window_name: tests
  options: {}
  panes:
  - focus: 'true'
    shell_command: nvm use v14.17.6
- window_name: web server
  options: {}
  panes:
  - focus: 'true'
    shell_command: nvm use v14.17.6
