session_name: school-buddy-ai
start_directory: /Users/mazulo/Dev/open-source/school-buddy-ai/

windows:
- window_name: editor
  options: {}
  panes:
  - focus: 'true'
    shell_command: workon school-buddy-ai && nvim
- window_name: shell
  options: {}
  panes:
  - focus: 'true'
    shell_command: workon school-buddy-ai
- window_name: tests
  options: {}
  panes:
  - focus: 'true'
    shell_command: workon school-buddy-ai
- window_name: web server
  options: {}
  panes:
  - focus: 'true'
    shell_command: workon school-buddy-ai
