session_name: service-hub
start_directory: /Users/mazulo/Dev/d7/avenidas/service-hub/

windows:
- window_name: editor
  options: {}
  panes:
  - focus: 'true'
    shell_command: export UV_PROJECT_ENVIRONMENT=${VIRTUAL_ENV} && workon service-hub && nvim
- window_name: shell
  options: {}
  panes:
  - focus: 'true'
    shell_command: export UV_PROJECT_ENVIRONMENT=${VIRTUAL_ENV} && workon service-hub
- window_name: tests
  options: {}
  panes:
  - focus: 'true'
    shell_command: export UV_PROJECT_ENVIRONMENT=${VIRTUAL_ENV} && workon service-hub
- window_name: web server
  options: {}
  panes:
  - focus: 'true'
    shell_command: export UV_PROJECT_ENVIRONMENT=${VIRTUAL_ENV} && workon service-hub
