session_name: web-b2b
start_directory: /Users/mazulo/dev/work/ashenlabs/closecare/web-b2b/

windows:
- window_name: editor
  options: {}
  panes:
  - focus: 'true'
    shell_command: nvm use v18.20.3 && nvim
- window_name: shell
  options: {}
  panes:
  - focus: 'true'
    shell_command: nvm use v18.20.3
- window_name: tests
  options: {}
  panes:
  - focus: 'true'
    shell_command: nvm use v18.20.3
- window_name: web server
  options: {}
  panes:
  - focus: 'true'
    shell_command: nvm use v18.20.3
