reload("user.plugins")
reload("user.setup")
reload("user.nvimtree")
reload("user.git")
reload("user.cmp")
reload("user.copilot-config")
reload("user.options")
reload("user.python")
reload("user.javascript")
reload("user.keymaps")
reload("user.treesitter")
reload("user.whichkey")
reload("user.go")
reload("user.formatters")
reload("user.autocommands")

vim.lsp.set_log_level("info")
