vim.keymap.set("n", "<leader>e", "<cmd>NvimTreeToggle<cr>")
vim.keymap.set("n", "<leader><space>", "<cmd>Telescope buffers<cr>")
vim.keymap.set("n", "<leader>fs", "<cmd>Telescope current_buffer_fuzzy_find<cr>")
vim.keymap.set("n", "<leader>ff", ":lua require'telescope.builtin'.find_files({no_ignore=true, hidden=true})<CR>")
vim.keymap.set("n", "<leader>fg", ":lua require'telescope.builtin'.live_grep()<CR>")
vim.keymap.set("n", "<leader>bc", "<cmd>Bdelete<CR>")
vim.keymap.set("n", "<leader>e", "<cmd>NvimTreeToggle<cr>")
vim.keymap.set("n", "<leader>q", ":<bar> bdelete #<CR> <C-U>bnext")
vim.keymap.set("n", "<leader>p", '"+p')

